### ISSUE TITLE
CP4BA 21.0.3 odm_configuration to reduce request values have no effect. 

### ISSUE THREAD

**Issue by TiloGit** [DecisionsDev/odm-docker-kubernetes#136]
Please don't tell me to raise this with CP team. 

Issue:  (on **CP4BA 21.0.3.IF018 [latest LTSR])** 
For DEV system I try to reduce the CPU and MEM request. (works great on other CP4BA components and the `ibm_cp4a_cr_production_FC_decisions.yaml` file suggest that it is possible. 
The KC / help as well: https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=parameters-operational-decision-manager

But the values aren't used. 
Also I couldn't find any logic which would pick these up (in the Ansible roles folder of CP4BA operator. )
nothing which read/uses: `decisionCenter.resources.requests.cpu`

Seems that since 22.0.1 the `roles\ODM\tasks\addparams-profile_size.yml` action on the CR values. 
Any plans to fix this in **21.0.3** (current supported LTSR) or document this as known issue?

Here the section of CP4BA CR file: 
```yaml
  odm_configuration:
    no_log: false
    debug: true ##doesn't use no_log: false
    decisionServerRuntime:
      enabled: true
      resources:
        requests:
          cpu: 31m
          memory: 256Mi
    decisionServerConsole:
      resources:
        requests:
          cpu: 31m
          memory: 256Mi
    # To enable the Authoring part
    decisionRunner:
      enabled: true
      resources:
        requests:
          cpu: 31m
          memory: 256Mi
    decisionCenter:
      enabled: true
      resources:
        requests:
          cpu: 31m
```

**Comment by PYLochou** [comment]
Hello, sorry for the delay, I didn't receive any notification, or maybe it slipped out of my attention :)

Your values should be used but it seems you didn't add the mandatory

```yaml
odm_configuration:
  deployment_profile_size: custom
```

in your CR (look for `deployment_profile_size` in https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=parameters-operational-decision-manager).

**Comment by TiloGit** [comment]
@PYLochou  thanks for you reply. 

on CP4BA 21.0.3 (LTSR) this doesn't work. 

I couldn't find any logic in 21.0.3 which would user/set the CPU/MEM values. 
here my ODM yaml section
```yaml
  odm_configuration:
    customization:
      authSecretRef: tso-odm-sec-mapping
    debug: true
    decisionCenter:
      enabled: true
      resources:
        requests:
          cpu: 31m
    decisionRunner:
      enabled: true
      resources:
        requests:
          cpu: 31m
          memory: 256Mi
    decisionServerConsole:
      resources:
        requests:
          cpu: 31m
          memory: 256Mi
    decisionServerRuntime:
      enabled: true
      resources:
        requests:
          cpu: 31m
          memory: 256Mi
    deployment_profile_size: custom
    no_log: false
```

merci

**Comment by PYLochou** [comment]
I just checked with latest code (iFix 22 I'd say) and it works as expected.

Here is an excerpt of my CR:

```yaml
spec:
  appVersion: 21.0.3
  ibm_license: accept
  shared_configuration:
    sc_deployment_profile_size: small
  odm_configuration:
    deployment_profile_size: custom
    decisionRunner:
      enabled: true
      resources:
        requests:
          cpu: 31m
          memory: 256Mi
```

and this is what I get:

```shell
oc get deployment odm-demo-2103-odm-decisionrunner -o jsonpath="{.spec.template.spec.containers[0].resources.requests.cpu}"
31m
```

So... I don't understand :(

The correct code has been provided about 18 months ago from my GitHub history, your iFix 18 is probably more recent...

Can you please check the source code in the CP4BA pod, and verify the following lines in roles/ODM-21.0.3/tasks/deploy.yml:

```yaml
- name: "include_tasks: addparams-profile_size"
  include_tasks: addparams-profile_size.yml
  when: odm_deployment_profile_size |lower != "custom"
```

(line 82)
Especially the when condition?

Thank you!
