### ISSUE TITLE
Sticky sessions are not enabled by ALB

### ISSUE THREAD

**Issue by eddycaballeroibm** [DecisionsDev/odm-docker-kubernetes#190]
With the current instructions for setting up alb, if you choose to run more than 1 decision center pod you will run into issues. This is because the provided configuration does not enable sticky sessions, which are required by decision center. 

A note should be added the readme that clarifies this. The two annotations below can be used to configure sticky sessions. 

```
alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
alb.ingress.kubernetes.io/target-type: ip
```

**Example**:

```
service:
  ingress:
    enabled: true
    class: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:iam::<AWS-AccountId>:server-certificate/mycompany"
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60 
      alb.ingress.kubernetes.io/target-type: ip

```
